name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.0.4'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project src/TestJl.jl
